### ISSUE TITLE
Sugestão de Cronograma

### ISSUE THREAD

**Issue by icaromh** [icaromh/truco-cerveja-churrasco#13]
- [x]  Escolha do Orientador
- [x]  Definição do Problema #4 
- [x]  Definição dos Objetivos e Solução #5 
- [x]  Definição da Abordagem de Desenvolvimento #8  
- [x]  Artefatos de Arquitetura #9  
- [x] Definição das Tecnologias #6 
- [x]  Validação #10 
- [x] Descrição da Solução #7 
- [x] Apresentação geral do Projeto #3 
- [x] Resumo #2 
- [x]  Entrega do Plano de Trabalho (mínimo, 3 orientações)
- [x]  Início do Desenvolvimento. 
- [x]  Prazo para re-entrega do Plano de Trabalho 
- [x]  Limite para primeira entrega.
- [x]  Primeira atualização do relatório.
- [x]  Limite para segunda entrega.
- [x]  Segunda atualização do relatório.
- [x]  Entrega do Relatório Parcial
- [x]  Preparação da Apresentação.
- [x]  Banca do Relatório Parcial
- [x]  Plano de ação para as férias.
- [ ]  Limite para a terceira entrega.
- [ ]  Férias
- [ ]  Limite para apresentação do trabalho de férias.
- [ ]  Atualização do relatório de andamento com as correções da banca.
- [ ]  Limite para a quarta entrega.
- [ ]  Atualização do relatório.
- [ ]  Entrega do Relatório de Andamento
- [ ]  Apresentação do Relatório de Andamento.
- [ ]  Banca do Relatório de Andamento
- [ ]  Limite para quinta entrega.
- [ ]  Limite para término da implementação. Início da validação com usuários.
- [ ]  Finalização do relatório de desenvolvimento.
- [ ]  Finalização da análise dos resultados.
- [ ]  Revisão final do relatório.
- [ ]  Entrega do Relatório Final
- [ ]  Apresentação para a banca final
- [ ]  Banca Final
- [ ]  Revisão do Relatório Final
- [ ]  Entrega do Relatório Final
